In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [4]:
arr = np.array(l)

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [7]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [9]:
arr1.ndim

2

In [10]:
arr.ndim

1

In [11]:
np.matrix(l)

matrix([[1, 2, 3, 4, 5]])

In [12]:
mat = np.matrix(l)

In [13]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [14]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [15]:
arr

array([1, 2, 3, 4, 5])

In [16]:
a = arr

In [17]:
a

array([1, 2, 3, 4, 5])

In [18]:
arr

array([1, 2, 3, 4, 5])

In [19]:
arr[0] = 100

In [20]:
arr

array([100,   2,   3,   4,   5])

In [21]:
a

array([100,   2,   3,   4,   5])

In [22]:
b = np.copy(arr)

In [23]:
b

array([100,   2,   3,   4,   5])

In [24]:
b[0] = 234

In [25]:
b

array([234,   2,   3,   4,   5])

In [26]:
arr

array([100,   2,   3,   4,   5])

In [27]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [28]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [29]:
(i*i for i in range(5))

<generator object <genexpr> at 0x000001C27FCE5380>

In [30]:
list((i*i for i in range(5)))

[0, 1, 4, 9, 16]

In [31]:
iterable = (i*i for i in range(5))

In [32]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [33]:
np.fromstring('23 45 67 89', sep=' ')

array([23., 45., 67., 89.])

In [34]:
np.fromstring('23,45,67,89', sep=',')

array([23., 45., 67., 89.])

In [35]:
arr

array([100,   2,   3,   4,   5])

In [36]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
arr.ndim

1

In [38]:
arr1.ndim

2

In [39]:
arr.size

5

In [40]:
arr1.size

6

In [41]:
arr.shape

(5,)

In [42]:
arr1.shape

(2, 3)

In [43]:
arr.dtype

dtype('int32')

In [44]:
arr1.dtype

dtype('int32')