In [1]:
import numpy as np

In [2]:
range(5)

range(0, 5)

In [3]:
list(range(5))

[0, 1, 2, 3, 4]

In [4]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
list(range(0.4,10.5))

TypeError: 'float' object cannot be interpreted as an integer

In [6]:
np.arange(.4,10.5)

array([ 0.4,  1.4,  2.4,  3.4,  4.4,  5.4,  6.4,  7.4,  8.4,  9.4, 10.4])

In [7]:
np.arange(.5,10.5,0.2)

array([ 0.5,  0.7,  0.9,  1.1,  1.3,  1.5,  1.7,  1.9,  2.1,  2.3,  2.5,
        2.7,  2.9,  3.1,  3.3,  3.5,  3.7,  3.9,  4.1,  4.3,  4.5,  4.7,
        4.9,  5.1,  5.3,  5.5,  5.7,  5.9,  6.1,  6.3,  6.5,  6.7,  6.9,
        7.1,  7.3,  7.5,  7.7,  7.9,  8.1,  8.3,  8.5,  8.7,  8.9,  9.1,
        9.3,  9.5,  9.7,  9.9, 10.1, 10.3])

In [8]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [9]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [10]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [16]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
arr = np.ones((3,4))

In [20]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [21]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [22]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
arr1 = np.eye(5)

In [26]:
import pandas as pd

In [27]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [28]:
np.random.rand(2,3)

array([[0.44066312, 0.19634988, 0.14901047],
       [0.76752249, 0.96060408, 0.48858965]])

In [30]:
np.random.randn(2,3)

array([[-0.50384851, -0.51464379, -0.16025184],
       [-0.3783463 , -0.60057892, -0.14509199]])

In [31]:
np.random.randint(1,5,(3,4))

array([[4, 3, 4, 4],
       [3, 3, 2, 1],
       [4, 4, 1, 3]])

In [32]:
arr2 = np.random.randint(1,5,(3,4))

In [33]:
arr2

array([[1, 3, 3, 1],
       [1, 4, 3, 1],
       [1, 2, 3, 3]])

In [34]:
arr2.size

12

In [35]:
arr2.shape

(3, 4)

In [36]:
arr2.reshape(6,2)

array([[1, 3],
       [3, 1],
       [1, 4],
       [3, 1],
       [1, 2],
       [3, 3]])

In [37]:
arr2.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [38]:
arr2.reshape(4,3)

array([[1, 3, 3],
       [1, 1, 4],
       [3, 1, 1],
       [2, 3, 3]])

In [39]:
arr2.reshape(4,-1)

array([[1, 3, 3],
       [1, 1, 4],
       [3, 1, 1],
       [2, 3, 3]])

In [40]:
arr2.reshape(2,2,3)

array([[[1, 3, 3],
        [1, 1, 4]],

       [[3, 1, 1],
        [2, 3, 3]]])

In [41]:
arr1 = np.random.randint(1,10,(5,6))

In [42]:
arr1

array([[3, 4, 1, 3, 9, 9],
       [1, 7, 1, 2, 7, 8],
       [7, 6, 5, 3, 5, 5],
       [6, 1, 9, 4, 3, 1],
       [8, 7, 1, 5, 5, 8]])

In [43]:
arr1 > 8

array([[False, False, False, False,  True,  True],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False, False, False, False]])

In [44]:
arr1[arr1 > 8]

array([9, 9, 9])

In [45]:
arr1

array([[3, 4, 1, 3, 9, 9],
       [1, 7, 1, 2, 7, 8],
       [7, 6, 5, 3, 5, 5],
       [6, 1, 9, 4, 3, 1],
       [8, 7, 1, 5, 5, 8]])

In [46]:
arr1[0]

array([3, 4, 1, 3, 9, 9])

In [47]:
arr1[0,[0,1]]

array([3, 4])

In [48]:
arr1[2:4,[2,3]]

array([[5, 3],
       [9, 4]])

In [49]:
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,3, (3,3))

In [51]:
arr1

array([[2, 1, 2],
       [1, 1, 2],
       [1, 2, 2]])

In [52]:
arr2

array([[2, 1, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [50]:
arr1 + arr2

array([[4, 2, 4],
       [3, 3, 4],
       [3, 4, 4]])

In [53]:
arr1 - arr2

array([[ 0,  0,  0],
       [-1, -1,  0],
       [-1,  0,  0]])

In [54]:
arr1 * arr2

array([[4, 1, 4],
       [2, 2, 4],
       [2, 4, 4]])

# matrix multiplication

In [55]:
arr1@arr2

array([[10,  8, 10],
       [ 8,  7,  8],
       [10,  9, 10]])

In [56]:
arr1 / arr2

array([[1. , 1. , 1. ],
       [0.5, 0.5, 1. ],
       [0.5, 1. , 1. ]])

In [57]:
arr1/0

C:\Users\prashant.shinde\AppData\Local\Temp\ipykernel_5724\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

# Numpy Broadcasting

In [58]:
arr = np.zeros((3,4))

In [59]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [61]:
a = np.array([1,2,3,4])

In [62]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [63]:
b = np.array([3,4,5])

In [64]:
arr+b

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [65]:
b = np.array([[3,4,5]])

In [66]:
arr+b.T

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [67]:
arr1 = arr+b.T

In [68]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [69]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [70]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [71]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [72]:
np.min(arr1)

3.0

In [73]:
np.max(arr1)

5.0