In [1]:
import numpy as np

In [4]:
arr = np.array([2,3,4,5,6,2,8,2,1,5,7,7,3,2,])

In [5]:
np.sort(arr)

array([1, 2, 2, 2, 2, 3, 3, 4, 5, 5, 6, 7, 7, 8])

In [6]:
np.searchsorted(arr,6)

10

In [7]:
np.searchsorted(arr,9)

14

In [9]:
arr1 = np.array([0,333,2354,4567,5,4,7,3,2345,4567,3,0,4,0,4,0])

In [10]:
np.count_nonzero(arr1)

12

In [11]:
np.where(arr1 > 0)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 14], dtype=int64),)

In [14]:
np.extract(arr1 > 20, arr1)

array([ 333, 2354, 4567, 2345, 4567])

In [15]:
arr1

array([   0,  333, 2354, 4567,    5,    4,    7,    3, 2345, 4567,    3,
          0,    4,    0,    4,    0])

In [16]:
arr1.byteswap()

array([         0, 1291911168,  839450624, -686751744,   83886080,
         67108864,  117440512,   50331648,  688455680, -686751744,
         50331648,          0,   67108864,          0,   67108864,
                0])

In [17]:
arr

array([2, 3, 4, 5, 6, 2, 8, 2, 1, 5, 7, 7, 3, 2])

In [18]:
arr1

array([   0,  333, 2354, 4567,    5,    4,    7,    3, 2345, 4567,    3,
          0,    4,    0,    4,    0])

In [19]:
a = np.copy(arr1)

In [20]:
a

array([   0,  333, 2354, 4567,    5,    4,    7,    3, 2345, 4567,    3,
          0,    4,    0,    4,    0])

In [21]:
b = arr1.view()
b

array([   0,  333, 2354, 4567,    5,    4,    7,    3, 2345, 4567,    3,
          0,    4,    0,    4,    0])

In [22]:
b[0] = 222

In [23]:
b

array([ 222,  333, 2354, 4567,    5,    4,    7,    3, 2345, 4567,    3,
          0,    4,    0,    4,    0])

In [24]:
arr1

array([ 222,  333, 2354, 4567,    5,    4,    7,    3, 2345, 4567,    3,
          0,    4,    0,    4,    0])

In [25]:
import numpy.matlib as nm

In [26]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [28]:
nm.ones((6,3))

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [29]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [30]:
arr1

array([ 222,  333, 2354, 4567,    5,    4,    7,    3, 2345, 4567,    3,
          0,    4,    0,    4,    0])

In [32]:
arr1 = np.random.randint([[2,3],[4,5]])
arr2 = np.random.randint([[6,7],[8,9]])

In [33]:
np.dot(arr1,arr2)

array([[13, 15],
       [21, 25]])

In [34]:
arr1@arr2

array([[13, 15],
       [21, 25]])