In [1]:
import numpy as np

# Numpy Array Manipulation

In [2]:
np.random.randint(1,10,(4,4))

array([[9, 3, 9, 1],
       [5, 2, 8, 9],
       [9, 8, 1, 9],
       [4, 5, 4, 9]])

In [3]:
arr = np.random.randint(1,10,(4,4))

In [4]:
arr

array([[9, 5, 1, 5],
       [1, 1, 2, 4],
       [6, 9, 8, 1],
       [2, 4, 3, 3]])

In [5]:
arr.reshape(8,2)

array([[9, 5],
       [1, 5],
       [1, 1],
       [2, 4],
       [6, 9],
       [8, 1],
       [2, 4],
       [3, 3]])

In [6]:
arr.T

array([[9, 1, 6, 2],
       [5, 1, 9, 4],
       [1, 2, 8, 3],
       [5, 4, 1, 3]])

In [7]:
arr.flatten()

array([9, 5, 1, 5, 1, 1, 2, 4, 6, 9, 8, 1, 2, 4, 3, 3])

In [8]:
np.expand_dims(arr)

TypeError: expand_dims() missing 1 required positional argument: 'axis'

In [9]:
np.expand_dims(arr,axis=1)

array([[[9, 5, 1, 5]],

       [[1, 1, 2, 4]],

       [[6, 9, 8, 1]],

       [[2, 4, 3, 3]]])

In [10]:
np.expand_dims(arr,axis=0)

array([[[9, 5, 1, 5],
        [1, 1, 2, 4],
        [6, 9, 8, 1],
        [2, 4, 3, 3]]])

In [11]:
data = np.array([[1],[2],[3]])

In [12]:
np.squeeze(data)

array([1, 2, 3])

In [13]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [14]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [15]:
np.roll(data,3)

array([[1],
       [2],
       [3]])

In [16]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [17]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# Numpy Binary Operations

In [19]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [20]:
arr1

array([[8, 8, 1, 1],
       [3, 7, 9, 9],
       [2, 3, 1, 8]])

In [21]:
arr2

array([[3, 5, 9, 8],
       [5, 2, 3, 5],
       [3, 9, 5, 4]])

In [22]:
arr1+arr2

array([[11, 13, 10,  9],
       [ 8,  9, 12, 14],
       [ 5, 12,  6, 12]])

In [23]:
arr1-arr2

array([[ 5,  3, -8, -7],
       [-2,  5,  6,  4],
       [-1, -6, -4,  4]])

In [24]:
arr1**arr2

array([[  512, 32768,     1,     1],
       [  243,    49,   729, 59049],
       [    8, 19683,     1,  4096]])

In [25]:
~arr1

array([[ -9,  -9,  -2,  -2],
       [ -4,  -8, -10, -10],
       [ -3,  -4,  -2,  -9]])

In [26]:
arr1>arr2

array([[ True,  True, False, False],
       [False,  True,  True,  True],
       [False, False, False,  True]])

# NUmpy String Operations

In [27]:
arr = np.array(["Pras","shin"])

In [28]:
arr

array(['Pras', 'shin'], dtype='<U4')

In [29]:
np.char.upper(arr)

array(['PRAS', 'SHIN'], dtype='<U4')

In [30]:
np.char.capitalize(arr)

array(['Pras', 'Shin'], dtype='<U4')

In [31]:
np.char.title(arr)

array(['Pras', 'Shin'], dtype='<U4')

In [32]:
arr1

array([[8, 8, 1, 1],
       [3, 7, 9, 9],
       [2, 3, 1, 8]])

In [33]:
np.sin(arr1)

array([[0.98935825, 0.98935825, 0.84147098, 0.84147098],
       [0.14112001, 0.6569866 , 0.41211849, 0.41211849],
       [0.90929743, 0.14112001, 0.84147098, 0.98935825]])

In [34]:
np.cos(arr1)

array([[-0.14550003, -0.14550003,  0.54030231,  0.54030231],
       [-0.9899925 ,  0.75390225, -0.91113026, -0.91113026],
       [-0.41614684, -0.9899925 ,  0.54030231, -0.14550003]])

In [35]:
np.tan(arr1)

array([[-6.79971146, -6.79971146,  1.55740772,  1.55740772],
       [-0.14254654,  0.87144798, -0.45231566, -0.45231566],
       [-2.18503986, -0.14254654,  1.55740772, -6.79971146]])

In [36]:
np.log10(arr1)

array([[0.90308999, 0.90308999, 0.        , 0.        ],
       [0.47712125, 0.84509804, 0.95424251, 0.95424251],
       [0.30103   , 0.47712125, 0.        , 0.90308999]])

In [37]:
np.exp(arr1)

array([[2.98095799e+03, 2.98095799e+03, 2.71828183e+00, 2.71828183e+00],
       [2.00855369e+01, 1.09663316e+03, 8.10308393e+03, 8.10308393e+03],
       [7.38905610e+00, 2.00855369e+01, 2.71828183e+00, 2.98095799e+03]])

In [39]:
np.power(arr1,2)

array([[64, 64,  1,  1],
       [ 9, 49, 81, 81],
       [ 4,  9,  1, 64]], dtype=int32)

In [40]:
np.mean(arr1)

5.0

In [41]:
np.median(arr1)

5.0

In [43]:
np.std(arr1)

3.265986323710904

In [46]:
np.var(arr1)

10.666666666666666

In [47]:
np.max(arr1)

9

In [48]:
np.min(arr1)

1

# Numpy Arithmatic Operations

In [51]:
arr1

array([[8, 8, 1, 1],
       [3, 7, 9, 9],
       [2, 3, 1, 8]])

In [50]:
arr2

array([[3, 5, 9, 8],
       [5, 2, 3, 5],
       [3, 9, 5, 4]])

In [52]:
arr1-arr2

array([[ 5,  3, -8, -7],
       [-2,  5,  6,  4],
       [-1, -6, -4,  4]])

In [53]:
np.subtract(arr1,arr2)

array([[ 5,  3, -8, -7],
       [-2,  5,  6,  4],
       [-1, -6, -4,  4]])

In [54]:
np.multiply(arr1,arr2)

array([[24, 40,  9,  8],
       [15, 14, 27, 45],
       [ 6, 27,  5, 32]])

In [55]:
np.mod(arr1,arr2)

array([[2, 3, 1, 1],
       [3, 1, 0, 4],
       [2, 3, 1, 0]])

In [56]:
np.power(arr1,arr2)

array([[  512, 32768,     1,     1],
       [  243,    49,   729, 59049],
       [    8, 19683,     1,  4096]])

# Numpy Statistical functions

In [57]:
arr1

array([[8, 8, 1, 1],
       [3, 7, 9, 9],
       [2, 3, 1, 8]])

In [58]:
np.mean(arr1)

5.0

In [59]:
np.std(arr1)

3.265986323710904

In [60]:
np.median(arr1)

5.0